language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
services:
  - postgresql
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -U postgres -c "create database rebel"
script:
  - coverage run --source=rebel -m unittest tests
after_success:
  - coveralls
